# Generated by Django 4.2.26 on 2025-11-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('ruc', models.CharField(blank=True, max_length=11, null=True, verbose_name='RUC')),
                ('phone', models.CharField(max_length=15, verbose_name='Celular')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ingresos Mensuales')),
                ('risk_rating', models.CharField(default='NORMAL', max_length=20, verbose_name='Calif. Central Riesgo')),
                ('is_blacklisted', models.BooleanField(default=False, verbose_name='Lista Negra')),
                ('district', models.CharField(default='Huánuco', max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
