# Generated by Django 4.2.26 on 2025-11-26 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('score_obtained', models.IntegerField(default=0, verbose_name='Puntaje Calculado')),
                ('suggested_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto Sugerido')),
                ('result', models.CharField(choices=[('APROBADO', '✅ Aprobado'), ('RECHAZADO', '❌ Rechazado'), ('REVISION_MANUAL', '🧐 Requiere Revisión')], max_length=20)),
                ('rules_breakdown', models.TextField(default='{}', verbose_name='Detalle de Reglas')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_evaluations', to='clients.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
