"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.26.
"""

from pathlib import Path
import os
from dotenv import load_dotenv  # <--- IMPORTANTE: Carga variables de entorno

# 1. Cargar el archivo .env (Si existe)
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# 2. Leemos la SECRET_KEY del entorno, o usamos una por defecto para desarrollo
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-clave-segura-hackaton-123')

# 3. DEBUG debe ser False en producción, pero True en Hackaton
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # --- TERCEROS ---
    'rest_framework',
    'corsheaders',

    # --- MIS APPS (MÓDULOS) ---
    'core',    # Núcleo / Utilidades
    'users',
    'clients',# Usuarios / Seguridad
    'credit_risk',
    'operations',
    'notifications',
    'integrations',
    'analytics',# 'clients', # Gestión de Clientes (Recién creado)
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # <--- CORS Primero
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# 4. CONFIGURACIÓN POSTGRESQL (Leyendo del .env)
# Si no encuentra .env, intentará usar SQLite para que no falle.
# Database
# Usamos SQLite por emergencia para que el equipo pueda trabajar YA MISMO.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# (Comenta o borra todo el bloque anterior que intentaba conectar a Postgres/os.getenv)


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'es-pe'
TIME_ZONE = 'America/Lima'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- CORS ---
CORS_ALLOW_ALL_ORIGINS = True 

# --- DRF ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
    ),
}

# --- USUARIO PERSONALIZADO ---
AUTH_USER_MODEL = 'users.User'

JAZZMIN_SETTINGS = {
    "site_title": "MiBanco Admin",
    "site_header": "Sistema Core Bancario",
    "welcome_sign": "Bienvenido al Panel de Control - Hackaton 2024",
    "copyright": "Mibanco Team",
    "search_model": ["clients.Client", "users.User"],
    "topmenu_links": [
        {"name": "Dashboard Ejecutivo", "url": "dashboard", "permissions": ["auth.view_user"]},
    ],
    "icons": {
        "users.User": "fas fa-user-shield",
        "clients.Client": "fas fa-users",
        "credit_risk.CreditEvaluation": "fas fa-chart-line",
        "operations.Loan": "fas fa-money-bill-wave",
    },
}