# Generated by Django 4.2.26 on 2025-11-26 16:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Cód. Operación')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Prestado')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Tasa Interés %')),
                ('term_months', models.IntegerField(default=12, verbose_name='Plazo (Meses)')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Desembolso')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Vencimiento Final')),
                ('current_status', models.CharField(choices=[('PENDIENTE', '⏳ Pendiente de Desembolso'), ('ACTIVO', '💰 Activo / Desembolsado'), ('PAGADO', '✅ Cancelado Totalmente'), ('MOROSO', '🚨 En Mora / Judicial')], default='PENDIENTE', max_length=20)),
                ('approved_by_user_id', models.IntegerField(blank=True, null=True, verbose_name='ID Aprobador (User)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='clients.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Préstamo Bancario',
                'verbose_name_plural': 'Cartera de Préstamos',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('transaction_type', models.CharField(choices=[('DESEMBOLSO', 'Desembolso (Salida)'), ('PAGO_CUOTA', 'Pago de Cuota (Entrada)')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('operation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('trace_code', models.CharField(blank=True, help_text='Hash único de operación', max_length=64)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='operations.loan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
